server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 666666
  thymeleaf:
    mode: HTML
    cache: false

mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.wt.bean








#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
#    username: root
#    password: 666666
##    driver-class-name:
#    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  config-location: classpath:mybatis-config.xml

#    mapper-location: classpath*:/mybatis/mapper/*.mapper
#    type-aliases-package: com.wt.bean
